#!/bin/bash

CHAMPSIM_PATH=$(pwd)/../ChampSim
TRACE_PATH=$(pwd)/../trace
DATA_PATH=$(pwd)/../raw_data
RESULT_PATH=$(pwd)/../result

DATA_ONE_PATH=$(pwd)/../raw_data/ONE
RESULT_ONE_PATH=$(pwd)/../result/ONE

REMOTE_USER="osm"
REMOTE_HOST="10.150.21.115"
REMOTE_PORT="50004"
REMOTE_DIR="/home/osm/workspace/TCP"
LOCAL_DIR="$(pwd)"
MAX_RUN_DISK=50
NUM_CORE=$(nproc)

# Champsim bin file 
SIMULATOR_NAMES_RUN=( 
# "default" 
"coalescing" "coalescing_block" "coalescing_ablock" "coalescing_aablock" "coalescing_aaablock"
"coalescing_tlb" "coalescing_tlb_block" "coalescing_tlb_ablock" "coalescing_tlb_aablock" "coalescing_tlb_aaablock"
# "perfect_tlb" "perfect_l1" "perfect_l2" "perfect_l3" 
# "all_spp" "all_ampm" "all_berti" "all_bingo" "all_ip" "all_next"
# "data_spp" "data_ampm" "data_berti" "data_bingo" "data_ip" "data_next" 
# "at_spp" "at_berti" "at_ip" 
# "at_ampm" "at_bingo" "at_next" "at_casp" "at_cdp"
# "l2_all_spp" "l2_all_ampm" "l2_all_berti" "l2_all_bingo" "l2_all_ip" "l2_all_next"
# "l2_data_spp" "l2_data_ampm" "l2_data_berti" "l2_data_bingo" "l2_data_ip" "l2_data_next" 
# "l2_at_berti" "l2_at_ip" 
# "l2_at_ampm" "l2_at_bingo" "l2_at_next" "l2_at_spp" 
# "l2_at_casp" "l2_at_cdp"
# "ptw_asap" 
# "ptw_ptempo_sp_l1" "ptw_ptempo_asp_l1" "ptw_ptempo_dp_l1" # "ptw_ptempo_mp_l1"
# "ptw_ptempo_sp_l2" "ptw_ptempo_asp_l2" "ptw_ptempo_dp_l2" # "ptw_ptempo_mp_l2"
# "ptw_ptempo_sp_l3" "ptw_ptempo_asp_l3" "ptw_ptempo_dp_l3" # "ptw_ptempo_mp_l3"
# "tlb_sp" "tlb_asp" "tlb_dp" # "tlb_mp"
# "tlb_miss"
# "tlb_sp_cache_l1" "tlb_asp_cache_l1" "tlb_dp_cache_l1" 
# "tlb_sp_cache_l2" "tlb_asp_cache_l2" "tlb_dp_cache_l2" 
# "tlb_sp_cache_l3" "tlb_asp_cache_l3" "tlb_dp_cache_l3" 
# "tlb_miss_cache_l1" "tlb_miss_cache_l2" "tlb_miss_cache_l3" 
# "tlb_sp_tlb_cache_l1" "tlb_asp_tlb_cache_l1" "tlb_dp_tlb_cache_l1" 
# "tlb_sp_tlb_cache_l2" "tlb_asp_tlb_cache_l2" "tlb_dp_tlb_cache_l2" 
# "tlb_sp_tlb_cache_l3" "tlb_asp_tlb_cache_l3" "tlb_dp_tlb_cache_l3" 
# "tlb_dp_slot_1" "tlb_dp_slot_2" "tlb_dp_slot_4" "tlb_dp_slot_8"
# "tlb_sp_1" "tlb_sp_4" "tlb_sp_16"  "tlb_sp_64" "tlb_sp_256"
# "tlb_asp_1" "tlb_asp_4" "tlb_asp_16" "tlb_asp_64" "tlb_asp_256" 
# "tlb_dp_1" "tlb_dp_4" "tlb_dp_16" "tlb_dp_64" "tlb_dp_256"
# "tlb_mp_1" "tlb_mp_4" "tlb_mp_16" "tlb_mp_64" "tlb_mp_256" 
# "sp_next_ip_no" "asp_next_ip_no" "dp_next_ip_no" "mp_next_ip_no"
# "sp_next_ip_next" "sp_next_ip_casp" "sp_next_ip_cdp" "sp_next_ip_bingo" "sp_next_ip_ampm" 
# "asp_next_ip_next" "asp_next_ip_casp" "asp_next_ip_cdp" "asp_next_ip_bingo" "asp_next_ip_ampm"
# "dp_next_ip_next" "dp_next_ip_casp" "dp_next_ip_cdp" "dp_next_ip_bingo" "dp_next_ip_ampm"

# "idle_default" 
# "idle_perfect_tlb" "idle_perfect_l1" "idle_perfect_l2" "idle_perfect_l3" 
# "idle_all_spp" "idle_all_ampm" "idle_all_berti" "idle_all_bingo" "idle_all_ip" "idle_all_next"
# "idle_data_spp" "idle_data_ampm" "idle_data_berti" "idle_data_bingo" "idle_data_ip" "idle_data_next" 
# "idle_at_spp" "idle_at_berti" "idle_at_ip" 
# "idle_at_ampm" "idle_at_bingo" "idle_at_next" "idle_at_casp" "idle_at_cdp"
# "idle_l2_all_spp" "idle_l2_all_ampm" "idle_l2_all_berti" "idle_l2_all_bingo" "idle_l2_all_ip" "idle_l2_all_next"
# "idle_l2_data_spp" "idle_l2_data_ampm" "idle_l2_data_berti" "idle_l2_data_bingo" "idle_l2_data_ip" "idle_l2_data_next" 
# "idle_l2_at_berti" "idle_l2_at_ip" 
# "idle_l2_at_ampm" "idle_l2_at_bingo" "idle_l2_at_next" "idle_l2_at_ampm" 
# "idle_l2_at_casp" "idle_l2_at_cdp"
# "idle_ptw_asap" 
# "idle_ptw_ptempo_sp_l1" "idle_ptw_ptempo_asp_l1" "idle_ptw_ptempo_dp_l1" # "idle_ptw_ptempo_mp_l1"
# "idle_ptw_ptempo_sp_l2" "idle_ptw_ptempo_asp_l2" "idle_ptw_ptempo_dp_l2" # "idle_ptw_ptempo_mp_l2"
# "idle_ptw_ptempo_sp_l3" "idle_ptw_ptempo_asp_l3" "idle_ptw_ptempo_dp_l3" # "idle_ptw_ptempo_mp_l3"
# "idle_tlb_sp" "idle_tlb_asp" "idle_tlb_dp" # "idle_tlb_mp"
# "idle_tlb_miss"
# "idle_tlb_sp_cache_l1" "idle_tlb_asp_cache_l1" "idle_tlb_dp_cache_l1" 
# "idle_tlb_sp_cache_l2" "idle_tlb_asp_cache_l2" "idle_tlb_dp_cache_l2" 
# "idle_tlb_sp_cache_l3" "idle_tlb_asp_cache_l3" "idle_tlb_dp_cache_l3" 
# "idle_tlb_miss_cache_l1" "idle_tlb_miss_cache_l2" "idle_tlb_miss_cache_l3" 
# "idle_tlb_sp_tlb_cache_l1" "idle_tlb_asp_tlb_cache_l1" "idle_tlb_dp_tlb_cache_l1" 
# "idle_tlb_sp_tlb_cache_l2" "idle_tlb_asp_tlb_cache_l2" "idle_tlb_dp_tlb_cache_l2" 
# "idle_tlb_sp_tlb_cache_l3" "idle_tlb_asp_tlb_cache_l3" "idle_tlb_dp_tlb_cache_l3" 
# "idle_tlb_dp_slot_1" "idle_tlb_dp_slot_2" "idle_tlb_dp_slot_4" "idle_tlb_dp_slot_8"
# "idle_tlb_sp_1" "idle_tlb_sp_4" "idle_tlb_sp_16"  "idle_tlb_sp_64" "idle_tlb_sp_256"
# "idle_tlb_asp_1" "idle_tlb_asp_4" "idle_tlb_asp_16" "idle_tlb_asp_64" "idle_tlb_asp_256" 
# "idle_tlb_dp_1" "idle_tlb_dp_4" "idle_tlb_dp_16" "idle_tlb_dp_64" "idle_tlb_dp_256"
# "idle_tlb_mp_1" "idle_tlb_mp_4" "idle_tlb_mp_16" "idle_tlb_mp_64" "idle_tlb_mp_256" 
# "idle_sp_next_ip_no" "idle_asp_next_ip_no" "idle_dp_next_ip_no" "idle_mp_next_ip_no"
# "idle_sp_next_ip_next" "idle_sp_next_ip_casp" "idle_sp_next_ip_cdp" "idle_sp_next_ip_bingo" "idle_sp_next_ip_ampm" 
# "idle_asp_next_ip_next" "idle_asp_next_ip_casp" "idle_asp_next_ip_cdp" "idle_asp_next_ip_bingo" "idle_asp_next_ip_ampm"
# "idle_dp_next_ip_next" "idle_dp_next_ip_casp" "dle_dp_next_ip_cdp" "idle_dp_next_ip_bingo" "idle_dp_next_ip_ampm"
)

SIMULATOR_NAMES=( 
# "default" 
"coalescing" "coalescing_block" "coalescing_ablock" "coalescing_aablock" "coalescing_aaablock"
"coalescing_tlb" "coalescing_tlb_block" "coalescing_tlb_ablock" "coalescing_tlb_aablock" "coalescing_tlb_aaablock"
# "perfect_tlb" "perfect_l1" "perfect_l2" "perfect_l3" 
# "all_spp" "all_ampm" "all_berti" "all_bingo" "all_ip" "all_next"
# "data_spp" "data_ampm" "data_berti" "data_bingo" "data_ip" "data_next" 
# "at_spp" "at_berti" "at_ip" 
# "at_ampm" "at_bingo" "at_next" "at_casp" "at_cdp"
# "l2_all_spp" "l2_all_ampm" "l2_all_berti" "l2_all_bingo" "l2_all_ip" "l2_all_next"
# "l2_data_spp" "l2_data_ampm" "l2_data_berti" "l2_data_bingo" "l2_data_ip" "l2_data_next" 
# "l2_at_berti" "l2_at_ip" 
# "l2_at_ampm" "l2_at_bingo" "l2_at_next" "l2_at_spp" 
# "l2_at_casp" "l2_at_cdp"
# "ptw_asap" 
# "ptw_ptempo_sp_l1" "ptw_ptempo_asp_l1" "ptw_ptempo_dp_l1" # "ptw_ptempo_mp_l1"
# "ptw_ptempo_sp_l2" "ptw_ptempo_asp_l2" "ptw_ptempo_dp_l2" # "ptw_ptempo_mp_l2"
# "ptw_ptempo_sp_l3" "ptw_ptempo_asp_l3" "ptw_ptempo_dp_l3" # "ptw_ptempo_mp_l3"
# "tlb_sp" "tlb_asp" "tlb_dp" # "tlb_mp"
# "tlb_miss"
# "tlb_sp_cache_l1" "tlb_asp_cache_l1" "tlb_dp_cache_l1" 
# "tlb_sp_cache_l2" "tlb_asp_cache_l2" "tlb_dp_cache_l2" 
# "tlb_sp_cache_l3" "tlb_asp_cache_l3" "tlb_dp_cache_l3" 
# "tlb_miss_cache_l1" "tlb_miss_cache_l2" "tlb_miss_cache_l3" 
# "tlb_sp_tlb_cache_l1" "tlb_asp_tlb_cache_l1" "tlb_dp_tlb_cache_l1" 
# "tlb_sp_tlb_cache_l2" "tlb_asp_tlb_cache_l2" "tlb_dp_tlb_cache_l2" 
# "tlb_sp_tlb_cache_l3" "tlb_asp_tlb_cache_l3" "tlb_dp_tlb_cache_l3" 
# "tlb_dp_slot_1" "tlb_dp_slot_2" "tlb_dp_slot_4" "tlb_dp_slot_8"
# "tlb_sp_1" "tlb_sp_4" "tlb_sp_16"  "tlb_sp_64" "tlb_sp_256"
# "tlb_asp_1" "tlb_asp_4" "tlb_asp_16" "tlb_asp_64" "tlb_asp_256" 
# "tlb_dp_1" "tlb_dp_4" "tlb_dp_16" "tlb_dp_64" "tlb_dp_256"
# "tlb_mp_1" "tlb_mp_4" "tlb_mp_16" "tlb_mp_64" "tlb_mp_256" 
# "sp_next_ip_no" "asp_next_ip_no" "dp_next_ip_no" "mp_next_ip_no"
# "sp_next_ip_next" "sp_next_ip_casp" "sp_next_ip_cdp" "sp_next_ip_bingo" "sp_next_ip_ampm" 
# "asp_next_ip_next" "asp_next_ip_casp" "asp_next_ip_cdp" "asp_next_ip_bingo" "asp_next_ip_ampm"
# "dp_next_ip_next" "dp_next_ip_casp" "dp_next_ip_cdp" "dp_next_ip_bingo" "dp_next_ip_ampm"

# "idle_default" 
# "idle_perfect_tlb" "idle_perfect_l1" "idle_perfect_l2" "idle_perfect_l3" 
# "idle_all_spp" "idle_all_ampm" "idle_all_berti" "idle_all_bingo" "idle_all_ip" "idle_all_next"
# "idle_data_spp" "idle_data_ampm" "idle_data_berti" "idle_data_bingo" "idle_data_ip" "idle_data_next" 
# "idle_at_spp" "idle_at_berti" "idle_at_ip" 
# "idle_at_ampm" "idle_at_bingo" "idle_at_next" "idle_at_casp" "idle_at_cdp"
# "idle_l2_all_spp" "idle_l2_all_ampm" "idle_l2_all_berti" "idle_l2_all_bingo" "idle_l2_all_ip" "idle_l2_all_next"
# "idle_l2_data_spp" "idle_l2_data_ampm" "idle_l2_data_berti" "idle_l2_data_bingo" "idle_l2_data_ip" "idle_l2_data_next" 
# "idle_l2_at_berti" "idle_l2_at_ip" 
# "idle_l2_at_ampm" "idle_l2_at_bingo" "idle_l2_at_next" "idle_l2_at_ampm" 
# "idle_l2_at_casp" "idle_l2_at_cdp"
# "idle_ptw_asap" 
# "idle_ptw_ptempo_sp_l1" "idle_ptw_ptempo_asp_l1" "idle_ptw_ptempo_dp_l1" # "idle_ptw_ptempo_mp_l1"
# "idle_ptw_ptempo_sp_l2" "idle_ptw_ptempo_asp_l2" "idle_ptw_ptempo_dp_l2" # "idle_ptw_ptempo_mp_l2"
# "idle_ptw_ptempo_sp_l3" "idle_ptw_ptempo_asp_l3" "idle_ptw_ptempo_dp_l3" # "idle_ptw_ptempo_mp_l3"
# "idle_tlb_sp" "idle_tlb_asp" "idle_tlb_dp" # "idle_tlb_mp"
# "idle_tlb_miss"
# "idle_tlb_sp_cache_l1" "idle_tlb_asp_cache_l1" "idle_tlb_dp_cache_l1" 
# "idle_tlb_sp_cache_l2" "idle_tlb_asp_cache_l2" "idle_tlb_dp_cache_l2" 
# "idle_tlb_sp_cache_l3" "idle_tlb_asp_cache_l3" "idle_tlb_dp_cache_l3" 
# "idle_tlb_miss_cache_l1" "idle_tlb_miss_cache_l2" "idle_tlb_miss_cache_l3" 
# "idle_tlb_sp_tlb_cache_l1" "idle_tlb_asp_tlb_cache_l1" "idle_tlb_dp_tlb_cache_l1" 
# "idle_tlb_sp_tlb_cache_l2" "idle_tlb_asp_tlb_cache_l2" "idle_tlb_dp_tlb_cache_l2" 
# "idle_tlb_sp_tlb_cache_l3" "idle_tlb_asp_tlb_cache_l3" "idle_tlb_dp_tlb_cache_l3" 
# "idle_tlb_dp_slot_1" "idle_tlb_dp_slot_2" "idle_tlb_dp_slot_4" "idle_tlb_dp_slot_8"
# "idle_tlb_sp_1" "idle_tlb_sp_4" "idle_tlb_sp_16"  "idle_tlb_sp_64" "idle_tlb_sp_256"
# "idle_tlb_asp_1" "idle_tlb_asp_4" "idle_tlb_asp_16" "idle_tlb_asp_64" "idle_tlb_asp_256" 
# "idle_tlb_dp_1" "idle_tlb_dp_4" "idle_tlb_dp_16" "idle_tlb_dp_64" "idle_tlb_dp_256"
# "idle_tlb_mp_1" "idle_tlb_mp_4" "idle_tlb_mp_16" "idle_tlb_mp_64" "idle_tlb_mp_256" 
# "idle_sp_next_ip_no" "idle_asp_next_ip_no" "idle_dp_next_ip_no" "idle_mp_next_ip_no"
# "idle_sp_next_ip_next" "idle_sp_next_ip_casp" "idle_sp_next_ip_cdp" "idle_sp_next_ip_bingo" "idle_sp_next_ip_ampm" 
# "idle_asp_next_ip_next" "idle_asp_next_ip_casp" "idle_asp_next_ip_cdp" "idle_asp_next_ip_bingo" "idle_asp_next_ip_ampm"
# "idle_dp_next_ip_next" "idle_dp_next_ip_casp" "dle_dp_next_ip_cdp" "idle_dp_next_ip_bingo" "idle_dp_next_ip_ampm"
)
